CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL UNIQUE,
  email VARCHAR(254) NOT NULL UNIQUE,
  username VARCHAR(20) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  status ENUM('active','muted','banned') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS avatar_appearances (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  body_tone VARCHAR(16) NOT NULL DEFAULT 'fern',
  hair_style VARCHAR(32) NOT NULL DEFAULT 'sprout',
  hair_color VARCHAR(16) NOT NULL DEFAULT 'moss',
  top_style VARCHAR(32) NOT NULL DEFAULT 'hoodie',
  top_color VARCHAR(16) NOT NULL DEFAULT 'plum',
  accessory VARCHAR(32) NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_appearance_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS rooms (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  public_id CHAR(36) NOT NULL UNIQUE,
  owner_user_id BIGINT UNSIGNED NULL,
  name VARCHAR(60) NOT NULL,
  description VARCHAR(240) NOT NULL DEFAULT '',
  width TINYINT UNSIGNED NOT NULL,
  height TINYINT UNSIGNED NOT NULL,
  access_mode ENUM('public','friends','private') NOT NULL DEFAULT 'public',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_room_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS room_tiles (
  room_id BIGINT UNSIGNED NOT NULL,
  x TINYINT UNSIGNED NOT NULL,
  y TINYINT UNSIGNED NOT NULL,
  height TINYINT UNSIGNED NOT NULL DEFAULT 0,
  floor_style VARCHAR(32) NOT NULL DEFAULT 'leaf-check',
  walkable BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (room_id, x, y),
  CONSTRAINT fk_tile_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS furniture_catalog (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  code VARCHAR(50) NOT NULL UNIQUE,
  name VARCHAR(80) NOT NULL,
  footprint_width TINYINT UNSIGNED NOT NULL DEFAULT 1,
  footprint_height TINYINT UNSIGNED NOT NULL DEFAULT 1,
  stack_height TINYINT UNSIGNED NOT NULL DEFAULT 0,
  asset_key VARCHAR(100) NOT NULL,
  price_coins INT UNSIGNED NOT NULL DEFAULT 0,
  enabled BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS furniture_items (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  catalog_id BIGINT UNSIGNED NOT NULL,
  owner_user_id BIGINT UNSIGNED NOT NULL,
  room_id BIGINT UNSIGNED NULL,
  x TINYINT UNSIGNED NULL,
  y TINYINT UNSIGNED NULL,
  rotation TINYINT UNSIGNED NOT NULL DEFAULT 0,
  state_json JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_item_catalog FOREIGN KEY (catalog_id) REFERENCES furniture_catalog(id),
  CONSTRAINT fk_item_owner FOREIGN KEY (owner_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_item_room FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS wallets (
  user_id BIGINT UNSIGNED PRIMARY KEY,
  coins BIGINT UNSIGNED NOT NULL DEFAULT 500,
  gems BIGINT UNSIGNED NOT NULL DEFAULT 0,
  CONSTRAINT fk_wallet_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS currency_transactions (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  currency ENUM('coins','gems') NOT NULL,
  amount BIGINT NOT NULL,
  reason_code VARCHAR(50) NOT NULL,
  reference_id CHAR(36) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ledger_user_time (user_id, created_at),
  CONSTRAINT fk_ledger_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

