ALTER TABLE avatar_appearances
  ADD COLUMN IF NOT EXISTS bottom_style VARCHAR(32) NOT NULL DEFAULT 'trousers',
  ADD COLUMN IF NOT EXISTS bottom_color VARCHAR(16) NOT NULL DEFAULT 'charcoal',
  ADD COLUMN IF NOT EXISTS shoes_style VARCHAR(32) NOT NULL DEFAULT 'trainers',
  ADD COLUMN IF NOT EXISTS shoes_color VARCHAR(16) NOT NULL DEFAULT 'cream';
