"""Repack the authored seven-row avatar sheets into true runtime atlases.

The reference sheets contain a planted idle in column 0 and six walk frames
in columns 1..6. They also contain seven authored views; the one missing
opposite profile is generated by mirroring its matching profile only. This is
kept explicit per gender so front/back rows never get accidentally swapped.
"""
from colorsys import rgb_to_hsv, hsv_to_rgb
from pathlib import Path
from PIL import Image
import numpy as np
from scipy import ndimage

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "apps/client/public/assets/avatars"
REFS = ROOT / "refs"
CELL_W, CELL_H = 220, 240
COMMON_AVATAR_H = 220
GRID = 7

# Runtime order: n, ne, e, se, s, sw, w, nw.
# The bearded sheet is ordered back, back-right, right, front-right, front,
# front-left, back-left. The braided sheet is ordered front, front-right,
# right, front-left, back, back-left, left-back. Keep these maps separate.
MALE_ROWS = [(0, False), (1, False), (2, False), (3, False), (4, False), (5, False), (2, True), (6, False)]
FEMALE_ROWS = [(4, False), (5, True), (2, False), (1, False), (0, False), (3, False), (2, True), (6, False)]

def tint_clothing(image: Image.Image, hue: float) -> Image.Image:
    image = image.convert("RGBA")
    px = image.load()
    for y in range(image.height):
        for x in range(image.width):
            r, g, b, a = px[x, y]
            if a and g > r * 1.05 and g > b * 1.05:
                _, s, v = rgb_to_hsv(r / 255, g / 255, b / 255)
                rr, gg, bb = hsv_to_rgb(hue, min(1, s * 1.05), v)
                px[x, y] = (round(rr * 255), round(gg * 255), round(bb * 255), a)
    return image

def cells(source: Image.Image, x_offset: int, y_offset: int):
    source = source.convert("RGBA")
    source_cell_w = source.width / GRID
    source_cell_h = source.height / GRID
    out = []
    for row in range(GRID):
        row_top = round(y_offset + row * source_cell_h)
        row_bottom = round(y_offset + (row + 1) * source_cell_h)
        alpha = np.asarray(source)[row_top:row_bottom, :, 3] > 10
        labels, count = ndimage.label(alpha)
        components = []
        for label in range(1, count + 1):
            ys, xs = np.where(labels == label)
            if len(xs) > 400:
                components.append((len(xs), int(xs.min()), int(xs.max()) + 1))
        # The reference sheets are tightly packed: source cell boundaries can
        # slice a shoe or hair. Anchor each cell on the seven main character
        # components instead, then use a fixed-width window for stable scale.
        centers = sorted(((left + right) // 2 for _, left, right in sorted(components, reverse=True)[:GRID]))
        if len(centers) != GRID:
            centers = [round((col + 0.5) * source_cell_w) for col in range(GRID)]
        row_cells = []
        for col in range(GRID):
            center = centers[col]
            half = round(source_cell_w / 2)
            left = center - half
            right = center + half
            top = row_top
            bottom = row_bottom
            cell = source.crop((max(0, left), top, min(source.width, right), min(source.height, bottom)))
            # The braided reference has a few stray braid pixels from the
            # preceding row at the very top of its profile row. They are not
            # part of the character in this cell.
            if y_offset == 10 and row == 2:
                cell.paste((0, 0, 0, 0), (0, 0, cell.width, min(24, cell.height)))
            # Source rows touch vertically. The authored avatar (including
            # footwear) is the dominant connected component; smaller detached
            # components are neighbouring-row fragments and must be removed.
            cell_alpha = np.asarray(cell)[..., 3] > 24
            labels, label_count = ndimage.label(cell_alpha)
            if label_count:
                areas = np.bincount(labels.ravel())
                areas[0] = 0
                main_label = int(areas.argmax())
                cleaned = np.array(cell, copy=True)
                cleaned[labels != main_label, 3] = 0
                cell = Image.fromarray(cleaned, "RGBA")
            row_cells.append(cell)
        out.append(row_cells)
    return out

def repack(source: Image.Image, destination: Path, row_map, x_offset: int, y_offset: int):
    src = cells(source, x_offset, y_offset)
    atlas = Image.new("RGBA", (CELL_W * GRID, CELL_H * 8), (0, 0, 0, 0))
    for target_row, (source_row, mirrored) in enumerate(row_map):
        for target_col in range(GRID):
            frame = src[source_row][target_col]
            # A few source cells touch the right edge of the reference sheet
            # and can be clipped to transparency. Keep the six-frame runtime
            # contract intact by reusing the nearest authored walk frame.
            if frame.getbbox() is None:
                for fallback_col in (target_col - 1, target_col + 1, 0, 1, 2, 3, 4, 5, 6):
                    if 0 <= fallback_col < GRID and src[source_row][fallback_col].getbbox() is not None:
                        frame = src[source_row][fallback_col]
                        break
            if mirrored:
                frame = frame.transpose(Image.Transpose.FLIP_LEFT_RIGHT)
            # Remove source padding, but preserve each pose's natural aspect
            # ratio. Only the height and foot baseline are shared; forcing a
            # fixed width visibly distorts profiles and diagonal poses.
            alpha = np.asarray(frame)[..., 3]
            ys, xs = np.where(alpha > 24)
            if len(xs):
                bbox = (int(xs.min()), int(ys.min()), int(xs.max()) + 1, int(ys.max()) + 1)
                frame = frame.crop(bbox)
                scaled_w = max(1, round(frame.width * COMMON_AVATAR_H / frame.height))
                frame = frame.resize((scaled_w, COMMON_AVATAR_H), Image.Resampling.LANCZOS)
            else:
                frame = Image.new("RGBA", (1, COMMON_AVATAR_H), (0, 0, 0, 0))
            grounded = Image.new("RGBA", (CELL_W, CELL_H), (0, 0, 0, 0))
            grounded.alpha_composite(frame, ((CELL_W - frame.width) // 2, CELL_H - COMMON_AVATAR_H - 2))
            frame = grounded
            atlas.alpha_composite(frame, (target_col * CELL_W, target_row * CELL_H))
    temporary = destination.with_suffix(destination.suffix + ".tmp")
    atlas.save(temporary, format="PNG", optimize=False, compress_level=6)
    temporary.replace(destination)

if __name__ == "__main__":
    male = Image.open(REFS / "Eight-Direction Bearded Avatar Sprite Sheet.png")
    female = Image.open(REFS / "Eight-direction braided avatar sprite sheet.png")
    variants = {
        "avatar-green": (male, MALE_ROWS),
        "avatar-midnight": (tint_clothing(male, .62), MALE_ROWS),
        "avatar-sunset": (tint_clothing(male, .04), MALE_ROWS),
        "avatar-lime": (female, FEMALE_ROWS),
        "avatar-purple": (tint_clothing(female, .78), FEMALE_ROWS),
        "avatar-coral": (tint_clothing(female, .02), FEMALE_ROWS),
    }
    for key, (source, mapping) in variants.items():
        repack(source, OUT / f"{key}-walk.png", mapping, 13 if mapping is MALE_ROWS else 19, 0 if mapping is MALE_ROWS else 10)
    print("Built six grounded eight-direction detailed atlases")
